### ISSUE TITLE
Financial Accounts Querying

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Heighliner#133]
In the wake of the "Clemson for Christmas" issue where an account that wasn't supposed be on my.newspring.cc was being returned by heighliner, would it be possible to provide a better way to query for accounts that should appear on Give? There is an `isPublic` boolean that we could query, but in practice many accounts are public that maybe shouldn't be.

Would it be possible to adjust the process so that `isPublic` is reliable? If not, possibly some other boolean for displaying an account on give? Relying on `PublicDescription` being blank or null feels hacky.

**Comment by dcs619** [comment]
@jonhorton @johnthepink In a perfect world, I'd use the following fields to determine which FinancialAccounts to display:
- [x] IsActive 
- [x] IsPublic
- [x] EndDate > Today
- [x] IsTaxDeductible (?)

Checking for a non-empty `PublicUrl` or `PublicDescription` feels like a hack, but there was probably a reason we went that route for launch.  Looking at the data, we'd need to ask Finance why so many accounts are currently marked Public.

**Comment by jbaxleyiii** [comment]
@johnthepink @dcs619 there were a couple of factors for this:
1. `isActive` means the fund should still expect money coming in
2. `isPublic` means the public can give to this fund. This is all children funds of public parents, as well as things like mission giving. It does not mean is public on my.newspring.cc

I think the correct fix for this would tie the current `<AddToCart/>` block to a page setting in Rock page builder. With a block there, an admin would select which funds.

The financial model isn't meant to control UI. We added in things like the public description and images to meet our needs for launch. Ideally, this is all controlled through a block setting.

I agree the current way is a hack 👎. I'd rather manage that hack until page builder is ready in Rock personally. This is a good block to try it out on

**Comment by dcs619** [comment]
@jbaxleyiii I agree with being able to manage until a better solution manifests.  

I'm confused by item 2 though, how else could the public give to those funds?  It seems like that flag would control what is displayed since my.newspring.cc is our giving platform.

**Comment by jbaxleyiii** [comment]
@dcs619 we have plans to have a mission specific page so you could select which mission funds to give to

**Comment by johnthepink** [comment]
We should be better set up to manage the hack at this point.
