### ISSUE TITLE
Error: Unknown argument "sizes" on field "images" of type "FinancialAccount".

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Heighliner#154]
https://app.getsentry.com/newspring-church/heighliner/issues/150961941/

```
Error: Unknown argument "sizes" on field "images" of type "FinancialAccount".

Error: Unknown argument "sizes" on field "images" of type "FinancialAccount".
```

**Comment by johnthepink** [comment]
@jbaxleyiii this is actually fixed now by rolling back to the old way, and I filed a new issue to go back and update to the new `url` attribute for give sections of the app.
