### ISSUE TITLE
Where have all the sermons gone?

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Heighliner#189]
## Steps to Reproduce
- Visit any Series (with sermons)
- Scroll to the bottom of the series description
## Buggy Behavior
- There are no sermon cards
## Expected Behavior
- There are sermon cards

**Comment by jbaxleyiii** [comment]
related sentry bug https://sentry.io/newspring-church/heighliner/issues/155367422/

**Comment by johnthepink** [comment]
This is fixed by clearing the cache, so keep that in mind when trying to reproduce.

**Comment by jbaxleyiii** [comment]
## Initial hunch

A query is done which pulls info incomplete info into the cache (maybe via selecting a reduced amount of fields. Then when the full query is requested, the cached data is missing needed fields to return sermons attached to a series
