### ISSUE TITLE
[RFC] Date Standardization

### ISSUE THREAD

**Issue by delianides** [NewSpring/Heighliner#247]
Right now there isn't any type of parity between the date values we set for queries; most are `MM/YY` but some are or need to be full date strings. 

On the flip side, it would be very helpful to specify what format the date information should be returned in. For example, creating a month chart for any giving day may require tick marks that should appropriately be the first letter of the month `J` for January; something like: 

```
transactions {
    ...
    date('m') as ChartTick
}
```

Making date/time results more flexible will only serve us better in the future.

**Comment by jbaxleyiii** [comment]
@delianides thanks for the idea!

Here is what I think it should do (this could apply to all current date fields across resolvers).

`date(format: String)` where `format` is a [Moment format string](http://momentjs.com/docs/#/displaying/format/)

We could create a formatDate under /util that would take a value and format and return that back (or just use moment inline). i.e.

```
date = ({ TransactionDateTime }, { format = "MM/YY" }) => (
  TransactionDateTime && moment(TransactionDateTime).format(format)
);
```

**Comment by delianides** [comment]
well apparently my use case isn't actually valid. In order to just a single letter for a month in moment you'd have to use your own locale. But I think its still a valid proposal.

would we have to apply your change to each resolver or is there a way to make it work from a single place?

**Comment by jbaxleyiii** [comment]
@delianides right now not from a single place 👎
