### ISSUE TITLE
Modularization pattern

### ISSUE THREAD

**Issue by lucasconstantino** [NewSpring/Heighliner#258]
Hi there

I've being studying your code to see how people are structuring GraphQL based backends, and I found that, in many aspects, you solved things the same way I solved when trying to modularize stuff. I've ended up creating [graphql-modules](https://github.com/lucasconstantino/graphql-modules) to solve schema modularization, and would love to get your input on that. Sorry to spam, I swear I only decided to contact here once I saw that bunch of string joins at [src/util/heighliner.js](https://github.com/NewSpring/Heighliner/blob/master/src/util/heighliner.js) :smile:

**Comment by jbaxleyiii** [comment]
@lucasconstantino that looks excellent! We should work on translating our app over to using your lib! Thanks for the heads up!
