### ISSUE TITLE
Heighliner Routing

### ISSUE THREAD

**Issue by delianides** [NewSpring/Heighliner#261]
Heighliner needs to 404 if the request is not under the `/graphql` sub path. Because the Amazon ALB doesn't support hostname routing requests to `api.newspring.cc` directory resolve to `api.newspring.cc/give/now` but serve as if they are `my.newspring.cc`. 

cc: /@jbaxleyiii

**Comment by meredithrouse** [comment]
@delianides Move to JIRA. SYS-3865.
