### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Heighliner#33]
We are currently using the Rock token to authenticate against the Heighliner service. This is ok for server to server communication, but it would really be great if we could authenticate from the client. This will provide faster load times to the end user, and reduce load on our server.

I don't totally know what that looks like yet but here are some thoughts:
1. The user's mongo id will be useful to provide scope when querying heighliner.
2. The Rock token will also be useful, if only for the ability to revoke the token.

Given that, we really shouldn't publish either of these things to the client if we are using them to authenticate. 

What if we use a public/private key system? Then, we could generate a public token by encrypting `[rocktoken]::[mongoid]::[email@email.com]::[salt of some kind]`, which we can then publish to the client. Only the party with the private key would be able to decrypt this token (heighliner). Then, heighliner can use that information to do it's bidding without having to do a DB lookup for the user.

This should result in a unique token for each user, and we can implement token expiration/refresh at some point too.

Thoughts? What am I missing? This seems like a fairly straight forward implementation that gives us client auth and security.

cc @jbaxleyiii

**Comment by johnthepink** [comment]
Or if DB lookups aren't a concern, a randomized token for each user that refreshes would probably be just as secure, and definitely simpler.

**Comment by jbaxleyiii** [comment]
@johnthepink are you thinking about adding them to the user profile?

**Comment by johnthepink** [comment]
@jbaxleyiii yep. Unique token for each user which either contains user info when decrypted, or can be used to lookup user information. Just need to ensure that something doesn't get published in both cases.

**Comment by jbaxleyiii** [comment]
@johnthepink I think that could work pretty easily! That and having a general auth level for data that is public (aka images, funds, etc)

**Comment by johnthepink** [comment]
@jbaxleyiii sweet! That's how I always did API authentication in rails. See https://github.com/lynndylanhurley/devise_token_auth

Basically a session token. Then just lookup by auth token for sensitive data. I'm thinking heighliner would need to manage which requests are sensitive.
