### ISSUE TITLE
CreatedDateTime vs TransactionDateTime

### ISSUE THREAD

**Issue by ghost** [NewSpring/Heighliner#34]
I think we want to display the date of the transaction (TransactionDateTime) rather than the date the record was created in rock (CreatedDateTime).  This is debatable though.  An example for ACH schedules that take almost a week to process, the schedule is for the 4th of every month, but the transaction isn't settled until the 11th.  Do we want to show April 4th (TransactionDateTime) or April 11th (CreatedDateTime)?

@johnthepink

**Comment by johnthepink** [comment]
@benwiley that makes sense to me

**Comment by johnthepink** [comment]
I would want it to show the date it came out of my bank account

**Comment by ghost** [comment]
Well the example happened to a staff member and the date it posted to his bank account was the 6th.  Not sure how we get that date...

**Comment by johnthepink** [comment]
Interesting. So he scheduled the 4th, hit his bank on the 6th, and Rock found it the 11th?

**Comment by ghost** [comment]
Yep, Rock found it the 11th because it waits for it to have a "settled" status in the payment processor.  We are changing this functionality so that Rock will soon show pending transactions.  When that happens the CreatedDateTime will likely match the TransactionDateTime.

**Comment by jbaxleyiii** [comment]
Fixed
